apiVersion: v1
kind: ConfigMap
metadata:
  name: nestjs-config
  namespace: nestjs
data:
  API_GATEWAY_PORT: "3000"
  API_GATEWAY_JWT_EXPIRES_IN: "1h"
  AUTH_JWT_EXPIRES_IN: "1d"
  THROTTLE_TTL: "60000"
  THROTTLE_LIMIT: "10"
  AUTH_SERVICE_HOST: "auth-service"
  AUTH_SERVICE_PORT: "4002"
  USER_SERVICE_HOST: "user-service"
  USER_SERVICE_PORT: "3001"
  PRODUCT_SERVICE_PORT: "3002"
  ORDER_SERVICE_PORT: "3003"
